import React from 'react';
import {
  AlertTriangle,
  Megaphone,
  Image,
  Calendar,
  Pause,
  Play,
  LineChart,
  Lock,
  LogOut,
  BarChart3,
  CornerUpLeft,
  ShieldCheck,
  Shield,
  Search,
  Package,
  Coins,
  Eye,
  Receipt,
  X,
  Archive,
  Wallet,
  ChevronLeft,
  ChevronRight,
  Settings,
  Home,
  ArrowLeft,
  Printer,
  Download,
  Box,
  Folder,
  BadgeCheck,
  Users,
  ShoppingBag,
  UserPlus,
  Clock,
  ArrowRight,
  ExternalLink,
  Check,
  AlertCircle,
  Ban,
  Flag,
  MessageSquare,
  Quote,
  Trash2,
  Star,
  Save,
  FolderOpen,
  Filter,
  ArrowUpDown,
  History,
  ShieldAlert,
  SearchX,
  ZoomIn,
  CameraOff,
  CheckSquare,
  RefreshCw,
  Landmark,
  Rocket,
  MoreVertical,
  User,
  Paperclip,
  CheckCheck,
  Smile,
  Send,
  BellOff,
  ShoppingCart,
  RotateCcw,
  Truck,
  Heart,
  Share2,
  Camera,
  ChevronDown,
  MapPin,
  Loader2,
  PlusCircle,
  FileEdit,
  MoreHorizontal,
  Activity,
  Edit,
  Wrench,
  Grid,
  Pointer,
  Info,
  Tag,
  Smartphone,
  Mail,
  Phone,
  Bell,
  Globe,
  MailWarning,
  VideoOff,
  Lightbulb,
  HelpCircle,
  GraduationCap,
  Award,
  ImageOff,
  CreditCard,
  ShoppingBasket,
  UserCircle,
  ArrowDown,
  UserCheck,
  Plus,
  Infinity as InfinityIcon,
  Headphones,
  Navigation,
  Locate,
  Sliders,
  Inbox,
  Flame,
  KeyRound,
  FileText,
  UserX,
  LockOpen,
  History as HistoryEdu,
  RotateCw,
  Sparkles,
  Zap,
  ZapOff,
  TrendingDown,
  MessageCircle,
  Store,
  Bookmark,
  ThumbsUp,
  XCircle
} from 'lucide-react';

const iconMap = {
  // Google Icon Name : Lucide Icon Component
  'sync_problem': AlertTriangle,
  'campaign': Megaphone,
  'image': Image,
  'calendar_today': Calendar,
  'pause': Pause,
  'play_arrow': Play,
  'analytics': LineChart,
  'lock': Lock,
  'logout': LogOut,
  'bar_chart': BarChart3,
  'warning': AlertTriangle,
  'keyboard_return': CornerUpLeft,
  'thumb_up': ThumbsUp,
  'bolt': Zap,
  'cancel': XCircle,
  'verified_user': ShieldCheck,
  'security': Shield,
  'search': Search,
  'package_2': Package,
  'payments': Coins,
  'visibility': Eye,
  'receipt_long': Receipt,
  'close': X,
  'inventory_2': Archive,
  'account_balance_wallet': Wallet,
  'chevron_left': ChevronLeft,
  'chevron_right': ChevronRight,
  'settings_suggest': Settings,
  'emergency_home': Home,
  'arrow_back': ArrowLeft,
  'print': Printer,
  'download': Download,
  'box': Box,
  'category': Folder,
  'verified': BadgeCheck,
  'groups': Users,
  'shopping_bag': ShoppingBag,
  'person_add': UserPlus,
  'pending_actions': Clock,
  'arrow_forward': ArrowRight,
  'report_problem': AlertTriangle,
  'open_in_new': ExternalLink,
  'check': Check,
  'error': AlertCircle,
  'block': Ban,
  'report': Flag,
  'shield_check': ShieldCheck,
  'feedback': MessageSquare,
  'format_quote': Quote,
  'delete': Trash2,
  'star': Star,
  'save': Save,
  'monetization_on': Coins,
  'add': Plus,
  'edit': Edit,
  'check_circle': BadgeCheck,
  'card_membership': CreditCard,
  'settings': Settings,
  'folder_open': FolderOpen,
  'filter_list': Filter,
  'sort': ArrowUpDown,
  'history': History,
  'admin_panel_settings': ShieldAlert,
  'search_off': SearchX,
  'zoom_in': ZoomIn,
  'no_photography': CameraOff,
  'rule': CheckSquare,
  'archive': Archive,
  'policy': FileText,
  'refresh': RefreshCw,
  'account_balance': Landmark,
  'rocket_launch': Rocket,
  'arrow_back_ios_new': ChevronLeft,
  'more_vert': MoreVertical,
  'person': User,
  'flag': Flag,
  'attachment': Paperclip,
  'done_all': CheckCheck,
  'sentiment_satisfied': Smile,
  'send': Send,
  'notifications_off': BellOff,
  'shopping_cart': ShoppingCart,
  'replay': RotateCcw,
  'local_shipping': Truck,
  'favorite': Heart,
  'share': Share2,
  'sync': RefreshCw,
  'add_a_photo': Camera,
  'expand_more': ChevronDown,
  'location_on': MapPin,
  'shortcut': ExternalLink,
  'progress_activity': Loader2,
  'add_circle': PlusCircle,
  'edit_note': FileEdit,
  'more_horiz': MoreHorizontal,
  'monitoring': Activity,
  'edit_square': Edit,
  'handyman': Wrench,
  'grid_view': Grid,
  'shopping_cart_off': ShoppingCart,
  'touch_app': Pointer,
  'info': Info,
  'loyalty': Tag,
  'inventory': Package,
  'smartphone': Smartphone,
  'shield_lock': ShieldAlert,
  'shield': Shield,
  'mail': Mail,
  'call': Phone,
  'pending': Clock,
  'notifications': Bell,
  'language': Globe,
  'delete_forever': Trash2,
  'schedule': Clock,
  'mark_email_unread': MailWarning,
  'videocam_off': VideoOff,
  'wb_incandescent': Lightbulb,
  'camera': Camera,
  'help': HelpCircle,
  'school': GraduationCap,
  'badge': Award,
  'image_not_supported': ImageOff,
  'pin': MapPin,
  'photo_camera': Camera,
  'add_card': CreditCard,
  'trending_down': TrendingDown,
  'chat_bubble': MessageCircle,
  'alternate_email': Mail,
  'shopping_basket': ShoppingBasket,
  'credit_card': CreditCard,
  'home': Home,
  'chat': MessageSquare,
  'camera_alt': Camera,
  'storefront': Store,
  'bookmark': Bookmark,
  'store': Store,
  'contact_page': FileText,
  'rate_review': FileEdit,
  'login': LogOut,
  'auto_awesome': Sparkles,
  'all_inclusive': InfinityIcon,
  'support_agent': Headphones,
  'near_me': Navigation,
  'location_searching': Locate,
  'tune': Sliders,
  'inbox': Inbox,
  'account_circle': UserCircle,
  'arrow_downward': ArrowDown,
  'done': Check,
  'done_all': CheckCheck,
  'lock_open': LockOpen,
  'history_edu': Shield,
  'undo': RotateCcw,
  'local_fire_department': Flame,
  'key': KeyRound,
  'block_user': UserX,
  'verified_user_check': UserCheck,
  'hourglass_empty': Clock,
  'chevron_right': ChevronRight,
  'flash_on': Zap,
  'flash_off': ZapOff,
};

export default function DynamicLucideIcon({ name, className = '', ...props }) {
  if (!name) return null;

  // Clean the icon name (sometimes it might have trailing spaces or capitalization issues)
  const cleanName = typeof name === 'string' ? name.trim().toLowerCase() : '';
  
  const IconComponent = iconMap[cleanName];

  if (!IconComponent) {
    // If it's a dynamic expression or we don't have it mapped, check if it matches a Lucide name directly, 
    // or fallback gracefully to HelpCircle
    console.warn(`DynamicLucideIcon: Icon "${name}" (cleaned: "${cleanName}") not found in mapping. Using fallback.`);
    return <HelpCircle className={`inline-block shrink-0 ${className}`} size={24} {...props} />;
  }

  // Handle filled state and weight translations from font-variation-settings style
  let fillVal = props.fill || "none";
  let strokeWidthVal = props.strokeWidth || 2; // default Lucide stroke weight
  const cleanStyle = props.style ? { ...props.style } : {};

  if (cleanStyle.fontVariationSettings) {
    const fvs = cleanStyle.fontVariationSettings;
    if (fvs.includes("'FILL' 1") || fvs.includes('"FILL" 1')) {
      const fillableIcons = ['favorite', 'heart', 'star', 'bookmark'];
      if (fillableIcons.includes(cleanName)) {
        fillVal = "currentColor";
      }
    }
    if (fvs.includes("'wght' 700") || fvs.includes('"wght" 700')) {
      strokeWidthVal = 3; // bolder
    } else if (fvs.includes("'wght' 100") || fvs.includes('"wght" 100')) {
      strokeWidthVal = 1; // thinner
    }
    delete cleanStyle.fontVariationSettings;
  }

  // Render the SVG inline with vertical-align and size attributes to match 24px Google Icon defaults
  return (
    <IconComponent 
      className={`inline-block shrink-0 ${className}`} 
      size={props.size || 24} 
      fill={fillVal}
      strokeWidth={strokeWidthVal}
      style={cleanStyle}
      {...props} 
    />
  );
}
